#!/usr/bin/env bash
#
# Publishes the wiki pages in this directory to the repository's GitHub wiki.
#
# The wiki is a separate git repository (…wiki.git) that GitHub does not create until a first page has
# been saved in the browser. These pages are kept here, under version control with the code they
# describe, rather than only in that repository: the wiki has no pull requests, no review and no CI, so
# a page edited only there is a claim nobody checked.
#
# Usage: wiki/push-wiki.sh "commit message"

set -euo pipefail

MESSAGE="${1:-Update the wiki}"

CONTENT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$CONTENT/.." && pwd)"
CLONE="$(mktemp -d)/wiki"
REMOTE=https://github.com/abdeljalilsennaoui/insurance-billing-qa-framework.wiki.git

git clone "$REMOTE" "$CLONE"

# --delete makes this directory the source of truth rather than an additive overlay. Without it a
# renamed or renumbered file leaves its predecessor behind: the screenshots were renumbered in the
# 1.2 release, and an additive sync would have left four images from the previous numbering sitting
# in the wiki, unreferenced and contradicting the pages that used to point at them.
#
# .git is excluded explicitly. rsync --delete against a clone would otherwise remove the repository
# it is about to commit into.
rsync -a --delete \
  --exclude .git \
  --exclude push-wiki.sh \
  --exclude README.md \
  --exclude screenshots \
  "$CONTENT"/ "$CLONE"/

# The images are not kept a second time here. docs/screenshots is the only copy — regenerated by
# scripts/capture-screenshots.sh from the UI suite — and it is copied in at publish time. A staged
# duplicate beside the pages would be one more list kept in step by somebody remembering, which is
# the mechanism behind DEF-014, and it had already drifted once.
rsync -a --delete "$ROOT/docs/screenshots"/ "$CLONE/screenshots"/

cd "$CLONE"
git add -A
git status --short

if git diff --cached --quiet; then
  echo "Nothing to publish: the wiki already matches this directory."
  exit 0
fi

git commit -m "$MESSAGE"
git push
echo
echo "Published: https://github.com/abdeljalilsennaoui/insurance-billing-qa-framework/wiki"
